venv_my_site/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('which_one.urls')),
    path(r'accounts/', include('accounts.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venv_my_site/my_site/which_one/urls.py
from django.urls import path, include
from . import views

app_name = 'which_one'
urlpatterns = [
    path(r'questionnaire_detail/<int:pk>/', views.Questionnaire_detail_page.as_view(), name='detail'),
    path(r'', views.Index_page.as_view(),name='index'),
    path(r'contact/', views.Contact_page, name='contact'),
    path(r'contact/complete/', views.Contact_complete_page.as_view(), name='complete'),
    path(r'new_questionnaire/', views.New_questionnaire_page.as_view(), name='new_questionnaire'),
    
]

venv_my_site/my_site/which_one/models.py
from django.db import models
from accounts.models import User
# Create your models here.

"""ユーザー投稿"""
class Category(models.Model):
    class Meta:
        verbose_name = "カテゴリー"
        verbose_name_plural = "カテゴリー"

    key = models.IntegerField(primary_key=True)
    name = models.CharField(verbose_name='カテゴリー', max_length=20)
    
    def __str__(self):
        return self.name

class Questionnaire(models.Model):
    class Meta:
        verbose_name = 'アンケート'
        verbose_name_plural = 'アンケート'
    
    user = models.ForeignKey(User, verbose_name='ユーザー', on_delete=models.PROTECT)
    title = models.CharField(verbose_name='タイトル', max_length=40)
    overview = models.TextField(verbose_name='概要', blank=False)
    text_A = models.TextField(verbose_name='質問文_A', blank=True)
    text_B = models.TextField(verbose_name='質問文_B', blank=True)
    image_A = models.ImageField(verbose_name='質問画像_A', blank=True, upload_to='images/',)
    image_B = models.ImageField(verbose_name='質問画像_B', blank=True, upload_to='images/',)
    file_A = models.FileField(verbose_name='質問音声_A', blank=True)
    file_B = models.FileField(verbose_name='質問音声_B', blank=True)
    category = models.ForeignKey(
                    Category, verbose_name='カテゴリー',
                    to_field='key',
                    on_delete=models.PROTECT,
    )
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    update_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)
    vote_A = models.IntegerField(default=0)
    vote_B = models.IntegerField(default=0)

    def __str__(self):
        return self.title


'''第三者投稿'''
# class ChoiceManager(models.Manager):
#     def create_choice(self,ip_address,questionnaire_id):
#         choice = self.model(  
#             questionnaire_id=questionnaire_id,
#             ip_address=ip_address,
#         )
#         try:
#             choice.save()
#         except:
#             return False
#         return True

class Choice(models.Model):
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
    ip_address = models.CharField(
        'IPアドレス',
        max_length=50,
        default=0,
    ) 
    vote_A = models.IntegerField(default=0)
    vote_B = models.IntegerField(default=0)
    # objects = ChoiceManager()
    
    def __str__(self):
        return self.questionnaire.title

class Comment(models.Model):
    class Meta:
        verbose_name = 'コメント'
    
    name = models.CharField('名前', max_length=20, default='名無し')
    questionnaire = models.ForeignKey(Questionnaire, on_delete=models.CASCADE)
    text = models.TextField(verbose_name='コメント',blank=False)
    created_date = models.DateTimeField(verbose_name='作成日時',auto_now_add=True)
    
    def __str__(self):
        return self.text
    


"""問い合わせ"""
class Contact(models.Model):
    class Meta:
        verbose_name = 'お問い合わせ'
    
    name = models.TextField(verbose_name='お名前', blank=False, max_length=15)
    contact_type = models.TextField(verbose_name='種類', blank=False)
    contents = models.TextField(verbose_name='お問い合わせ内容')
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)

    def __str__(self):
        return self.name

venv_my_site/my_site/which_one/forms.py
from django import forms
from .models import Contact, Questionnaire,Category

class ContactForm(forms.Form):

    CHOICES = (
    ("0", "ご意見"),
    ("1", "ご報告"),
    ("2", "その他")
    )

    name = forms.CharField(label='お名前',
                max_length=15,
            )
            
    contact_type = forms.ChoiceField(label='お問い合わせの種類',
                                widget=forms.Select, 
                                choices=CHOICES  # リストを指定する
                    )
    contents = forms.CharField(label='お問い合わせ内容',widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-12 my-3'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前'

        self.fields['contact_type'].widget.attrs['class'] = 'form-control col-12 my-3'

        self.fields['contents'].widget.attrs['class'] = 'form-control col-12 my-3'
        self.fields['contents'].widget.attrs['placeholder'] = 'お問い合わせ内容はこちら'
    

class NewQuestionnaireForm(forms.ModelForm):
    class Meta:
        model = Questionnaire
        fields = ('title','overview','text_A','text_B','image_A','image_B','file_A','file_B','category')
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image_A'].widget.attrs["onchange"] = "imgPreView(event);"
        self.fields['image_B'].widget.attrs["onchange"] = "imgPreView(event);"
        self.fields['category'].widget.attrs["onchange"] = "categoryView(event);"

venv_my_site/my_site/which_one/views.py
from django.shortcuts import render, get_object_or_404,redirect
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import ContactForm, NewQuestionnaireForm
from django.forms import formset_factory, modelformset_factory
from .models import Contact,Questionnaire,Category
from accounts.models import User
from django.urls import reverse_lazy
from django.contrib import messages
# Create your views here.

"""一覧ページ"""
class Index_page(generic.ListView):
    context_object_name = 'questions_list'
    model = Questionnaire
    template_name = 'which_one/index.html'

    def get_queryset(self):
        questions = Questionnaire.objects.all().order_by('-created_at')
        return questions


"""問い合わせページ"""
def Contact_page(request):
    form_class = ContactForm(request.POST or None)
    if form_class.is_valid():
        # contact = ContactForm
        # Contact_page.name = form_class.cleaned_data['name']
        # Contact_page.contact_type = form_class.cleaned_data['contact_type']
        # Contact_page.contents = form_class.cleaned_data['contents']

        Contact.objects.create(
            name= form_class.cleaned_data['name'],
            contact_type = form_class.cleaned_data['contact_type'],
            contents = form_class.cleaned_data['contents']
        )
        return redirect('which_one:complete')
    return render(request, 'which_one/contact.html', {'form': form_class})


"""問い合わせ完了ページ"""
class Contact_complete_page(generic.TemplateView):
    template_name = 'which_one/cotact_complete.html'


"""新規作成ページ"""
class New_questionnaire_page(generic.CreateView):
    template_name = 'which_one/new_questionnaire.html'
    # model = Questionnaire
    # fields = ('title','overview','text_A','text_B','image_A','image_B','file_A','file_B','category')
    form_class = NewQuestionnaireForm
    success_url = reverse_lazy('which_one:index')
    
    # def get(self, request):
    #     NewFormSet =  modelformset_factory(Questionnaire, form=NewQuestionnaireForm, extra=2)
    #     if request.method == 'GET':
    #         initial_images = [{'image': i.image, 'image_url': i.image.url} for i in form if i.image]
    #         formset = NewFormSet(initial=initial_images)
    #     return render(request, template_name, {'formset': formset})

    def form_valid(self,form):
        page = form.save(commit=False)
        if self.request.user.is_anonymous:
            gest_user = User.objects.get(pk=1)
            page.user = gest_user
        else:
            page.user = self.request.user
        page.save()
        return super().form_valid(form)


"""詳細ページ"""
class Questionnaire_detail_page(generic.DetailView):
    model = Questionnaire
    template_name = 'which_one/questionnaire_detail.html'
    context_object_name = 'Questionnaire'
    
    # def get_context_data(self, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     post = context.get("object")
    #     # do something
    #     return context
    
    # def get_context_data(self, **kwargs):
    #     context = super(Questionnaire_detail_page, self).get_context_data(**kwargs)
    #     return context

    def post(self,request,pk):
        obj = Questionnaire.objects.get(pk=pk)
        if request.method == "POST":
            if "item-A" == request.POST['accessible-radio']:
                obj.vote_A +=1
                obj.save()
            if "item-B" == request.POST['accessible-radio']:
                obj.vote_B +=1
                obj.save()
            return render(request, 'which_one/questionnaire_detail.html',{'Questionnaire':obj})



def get_client_ip(request):
    '''
    IPアドレスを取得する
    '''
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

venv_my_site/my_site/which_one/templates/which_one/contact.html
{% extends "base.html" %}

{% block content %}
    {% block title %}
    <div class="col-lg-3"></div>
        <h1 class="col-sm-10 my-4">お問い合わせ</h1>
    {% endblock %}
    <div class="container">
        <div class="row">
            <form method="POST">
                {% csrf_token %}         
                {% for field in form %}
                    <div class="form-group row">
                        <label for="{{ field.id_for_label }}" class="col-sm-5 col-form-label">
                            <strong>{{ field.label_tag }}</strong>
                        </label>
                        <div class="col-sm-8">
                            {{ field }}
                        </div>
                    </div>
                {% endfor %}
                <div class="col-sm-7">
                    <button class="btn btn-primary mb-2" type="submit">送信</button>
                    <a href='{% url "which_one:index" %}' class='btn btn-outline-secondary mb-2'>TOPに戻る</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

venv_my_site/my_site/which_one/templates/which_one/cotact_complete.html
{% extends "base.html" %}
{% block content %}

    {% block title %}
    <h1 class="my-4">送信完了</h1>
    <h2 class="">ご連絡ありがとうございます。</h2>
    {% endblock %}

<a href='{% url "which_one:index" %}' class='btn btn-outline-secondary mb-2'>TOPに戻る</a>
{% endblock %}

venv_my_site/my_site/which_one/templates/which_one/index.html
{% extends 'base.html' %}

{% block description %}
<div class="site-description">
  <div class="mt-3 site-description-inner">
    <p>Questionnaireは、ユーザーの投稿に対して投票を行うサービスです。</p>
  </div>
</div>
{% endblock %}

{% block content %}
<!-- Page Content -->
{% block title %}<h1 class="pt-4">Questionnaires</h1>{% endblock %}

<div class="row">
  {% for question in questions_list %}  
  <div class="col-lg-4 col-md-6 mb-4 my-3">
    <div class="card h-100">
      <div class="card-body">
        <h6 class="card-title">
          <a href="{% url 'which_one:detail' question.id %}">{{ question.title }}</a>
        </h6>
        <p class="card-text">{{ question.overview|truncatechars:35 }}</p>
      </div>
      <div class="card-footer">
        <div class="left-text"><small class="text-muted">{{question.category.name}}</small></div>
        <div class="right-text"><small class="text-muted">{{ question.created_at }}</small></div>
      </div>
    </div>
  </div>
  {% endfor %}
</div>
<!-- /.row -->
{% endblock %}

venv_my_site/my_site/which_one/templates/which_one/new_questionnaire.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div>
    {% block title %}<h1>新規作成</h1>{% endblock %}
    <script type="text/javascript" src="{% static 'javascript/createView.js' %}"></script>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div>
            <table>
                <h2>{{ form.title.label }}</h2>
                <h5 class="mb-4">{{ form.title }}</h5>
            </table>
            <table>
                <h2>{{form.overview.label}}</h2>
                <h5 class="mb-4">{{ form.overview }}</h5>
            </table>
            <table>
                <h2>アンケート対象</h2>
                <div class="mb-2">{{ form.category }}</div>
            </table>
            
            <script>
                function categoryView(event) {
                    var eventID = event.target.selectedIndex;
                    if (eventID == 1) {
                        document.getElementById("questionnaire").innerHTML =
                            `<div>
                                <span>{{ form.text_A }}</span>
                                <span>{{ form.text_B }}</span>
                            </div>`
                        document.getElementById("id_text_A").setAttribute("required","")
                        document.getElementById("id_text_B").setAttribute("required","")
                    }
                    else if (eventID == 2){
                        document.getElementById("questionnaire").innerHTML =
                        `<table>
                            <td>{{ form.image_A }}</td>
                            <td>{{ form.image_B }}</td>
                        </table>
                        <table>
                            <td><div id="preview_A"></div></td>
                            <td><div id="preview_B"></div></td>
                        </table>`
                        document.getElementById("id_image_A").setAttribute("required","")
                        document.getElementById("id_image_B").setAttribute("required","")
                    }
                    else {
                        document.getElementById("questionnaire").innerHTML =""
                    }         
                }   
            </script>

            <table id="questionnaire"></table>
        </div>
        <button type="submit" class="btn btn-primary mt-2 mb-2">送信</button>
        <a href='{% url "which_one:index" %}' class='btn btn-outline-secondary mt-2 mb-2'>TOPに戻る</a>
    </form>
</div>

{% endblock %}

venv_my_site/my_site/which_one/templates/which_one/questionnaire_detail.html
{% extends 'base.html' %}
{% block content %}
{% block title %}<h1></h1>{% endblock %}
{% load extra_tags %}

<table class="table">
  <small>{{ Questionnaire.user }}</small>    
  <h1>{{ Questionnaire.title }}</h1>
  <div class="detail-about"><small>投稿日：{{ Questionnaire.created_at }} 　投稿内容：{{ Questionnaire.category.name }}</small></div>
  <h2 class="detail-overview">概要</h2>
  <p>{{ Questionnaire.overview }}</p>

  <span class="votes">投票数　 A : {{ Questionnaire.vote_A }} B : {{ Questionnaire.vote_B }}</span>
  {% if Questionnaire.vote_A == 0 and Questionnaire.vote_B == 0 %}
  <div class="vote-rate">
    <div id="nothing-vote" style="width:100%"></div>
  </div>
  {% else %}
  <div class="vote-rate">
    <div id="vote-B" style="width:{{ Questionnaire.vote_A | calc:Questionnaire.vote_B }}"></div>
  </div>
  {% endif %}
  
  {% if Questionnaire.category.key == 0 %}
    <div class="col-lg-6" id="box-container-A">
      <h3>A : {{ Questionnaire.text_A }}</h3>
    </div>  
    <div class="col-lg-6 " id="box-container-B">
      <h3>B : {{ Questionnaire.text_B }}</h3>
    </div>
  {% elif Questionnaire.category.key == 1 %}
    <div class="col-lg-6" id="box-container-A">
      <h3>A</h3>
      <img src="{{ Questionnaire.image_A.url }}/" width="250" height="auto"/>
    </div> 
    <div class="col-lg-6" id="box-container-B">
      <h3>B</h3>
      <img src="{{ Questionnaire.image_B.url }}/" width="250" height="auto"/>
    </div>
  {% elif Questionnaire.category.key == 2 %}
      <p>{{ Questionnaire.file_A }}</p>
      <p>{{ Questionnaire.file_B }}</p>
  {% endif %}
  </div>
</table>

<form method="POST">
{% csrf_token %}
  <fieldset>
    <input id="item-A" class="radio-inline__input" type="radio" name="accessible-radio" value="item-A" required/>
    <label class="radio-inline__label" for="item-A">
        左：A
    </label>
    <input id="item-B" class="radio-inline__input" type="radio" name="accessible-radio" value="item-B"/>
    <label class="radio-inline__label" for="item-B">
        右：B
    </label>
    <input type="submit" style="width:10%"　value="投票">
  </fieldset>
</form>
{% endblock %}