venv_my_site/my_site/accounts/urls.py
from django.urls import path, include
from django.views.generic import TemplateView
from . import views

app_name = 'accounts'
urlpatterns = [
    #path(r'login/', views.LoginView.as_view(), name='login'),
    path(r'login/', views.Login_request.as_view() , name='login'),
    path(r'logout/', views.LogoutView.as_view(), name="logout"),
    path(r'profile/',views.ProfileView.as_view(), name='profile'),
    path(r'settings/',views.ProfileView.as_view(), name='settings'),
    path(r'settings/password/',views.ProfileView.as_view(), name='password'),
    path(r'create/', views.UserCreateView.as_view(),name="create"),
    path(r'', include('which_one.urls')),
]

venv_my_site/my_site/my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'', include('which_one.urls')),
    path(r'accounts/', include('accounts.urls')),
] 

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venv_my_site/my_site/which_one/urls.py
from django.urls import path, include
from . import views

app_name = 'which_one'
urlpatterns = [
    path(r'questionnaire_detail/<int:pk>/', views.Questionnaire_detail_page.as_view(), name='detail'),
    path(r'', views.Index_page.as_view(),name='index'),
    path(r'contact/', views.Contact_page, name='contact'),
    path(r'contact/complete/', views.Contact_complete_page.as_view(), name='complete'),
    path(r'new_questionnaire/', views.New_questionnaire_page.as_view(), name='new_questionnaire'),
    
]

venv_my_site/my_site/templates/base.html
{% load static %}
<!DOCTYPE html>

<html lang="ja" style="height:100%;">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Questionnaire</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/homepage.css' %}" rel="stylesheet">

</head>

<body>
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark fixed-top top-nav">
    <div class="container">
      <a class="navbar-brand" href="{% url 'which_one:index' %}">Questionnaire</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'which_one:index' %}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">About</a>
          </li>
          {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:profile' %}">{{ user.get_username }}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:logout' %}">ログアウト</a>
          </li>
          {% else %}
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:create' %}">ゲストユーザー</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'accounts:login' %}">ログイン</a>
          </li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <!-- Page Content -->
  {% block description %}
  {% endblock %}
  <div class="container">

    <div class="row">

      <div class="col-lg-3">
        <!-- <h1 class="my-3"></h1> -->
        <div class="list-group my-3 pt-3">
          <a href="{% url 'which_one:index' %}" class="list-group-item">TOP</a>
          <a href="{% url 'which_one:new_questionnaire' %}" class="list-group-item">新規投稿</a>
          <a href="{% url 'which_one:contact' %}" class="list-group-item">お問い合わせ</a>
          <!-- <a href="#" class="list-group-item">Category 3</a> -->
        </div>
      </div>
      <!-- /.col-lg-3 -->
      <div class="col-lg-9">
      {% block content %}

        {% block title %}

        {% endblock %}

      {% endblock %}
      </div>
    </div>
  </div>
  <!-- Footer -->
  <footer class="py-3">
    <div class="container">
      <p class="m-0 text-center text-white">Copyright &copy; Questionnaire 2021</p>
    </div>
  </footer>

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

</body>

</html>